### ISSUE TITLE
CZDB 文件已加密，请问可以提供 Key 吗？

### ISSUE THREAD

**Issue by Ackerven** [nmgliangwei/qqwry#1]
CZDB 文件需要 Key 解密 才能使用。

![image](https://github.com/user-attachments/assets/2c869f9a-dc2e-4405-acb1-12fbfacf3414)

**从取消公众号发布到现在连数据库文件也开始加密，不难看出纯真的真实意图。**

**纯真社区版IP库的基因已经突变...**

![image](https://github.com/user-attachments/assets/d1afa7ee-3875-4404-82ea-8032ee4ca37b)

**Comment by nmgliangwei** [comment]
呃…我抽时间看下怎么处理一下吧，暂时先用dat吧

**Comment by nmgliangwei** [comment]
呃…我抽时间看下怎么处理一下吧，暂时先用dat吧

**Comment by Ackerven** [comment]
好的，谢谢你

**Comment by liucx1201** [comment]
> 呃…我抽时间看下怎么处理一下吧，暂时先用dat吧

期待大佬

**Comment by nmgliangwei** [comment]
想着解密在重新用一个固定的密钥加密，然后把密钥公开来着，今天抽时间试了一下发现有点问题，看看大家是否时间搞一下？最近工作太忙没太多时间折腾。。

**Comment by Xeath** [comment]
> 想着解密在重新用一个固定的密钥加密，然后把密钥公开来着，今天抽时间试了一下发现有点问题，看看大家是否时间搞一下？最近工作太忙没太多时间折腾。。

纯真社区版授权说明中有一个重点需要留意：

> 3. 纯真社区版IP库仅授权给您使用，每个授权用户均有自己独特的下载链接，若发现您擅自公开、转让该链接给其他方使用，我们有权停止您使用纯真社区版IP库更新服务，并追究您的相关责任。

虽然只是说到公开下载链接可能会追责，但是这个逆向的做法也是存在法律风险，博主请谨慎。
社区版可以免费使用（包括商用），有需要应该引导用户自己去申请授权（基本上能通过）。

**Comment by nmgliangwei** [comment]
@Xeath 嗯，是的，推荐大家自行申请吧
